// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrEGfcjSzowCOMQ8xJXpDmCMI-phWg5E',
    appId: '1:88063366957:web:fe4b726f49b8af9ccae5a4',
    messagingSenderId: '88063366957',
    projectId: 'adopteacandidat3',
    authDomain: 'adopteacandidat3.firebaseapp.com',
    databaseURL: 'https://adopteacandidat3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adopteacandidat3.appspot.com',
    measurementId: 'G-JP5EPJLN9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHwYCOgi_dReGCSn2OA1_Mj9L1Xnxt27o',
    appId: '1:88063366957:android:f69efbbe61e2d8dccae5a4',
    messagingSenderId: '88063366957',
    projectId: 'adopteacandidat3',
    databaseURL: 'https://adopteacandidat3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adopteacandidat3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfGI69Q1_KeoM4MiccV51jczrd3jv3w8',
    appId: '1:88063366957:ios:8945be2bbf686dd0cae5a4',
    messagingSenderId: '88063366957',
    projectId: 'adopteacandidat3',
    databaseURL: 'https://adopteacandidat3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adopteacandidat3.appspot.com',
    iosClientId: '88063366957-4mr3af4f3ae4f2f13pkc3le68t64llmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.adopteACandidate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfGI69Q1_KeoM4MiccV51jczrd3jv3w8',
    appId: '1:88063366957:ios:8945be2bbf686dd0cae5a4',
    messagingSenderId: '88063366957',
    projectId: 'adopteacandidat3',
    databaseURL: 'https://adopteacandidat3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adopteacandidat3.appspot.com',
    iosClientId: '88063366957-4mr3af4f3ae4f2f13pkc3le68t64llmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.adopteACandidate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByrEGfcjSzowCOMQ8xJXpDmCMI-phWg5E',
    appId: '1:88063366957:web:270ff30b1c71e378cae5a4',
    messagingSenderId: '88063366957',
    projectId: 'adopteacandidat3',
    authDomain: 'adopteacandidat3.firebaseapp.com',
    databaseURL: 'https://adopteacandidat3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adopteacandidat3.appspot.com',
    measurementId: 'G-J8GXSZZDQ8',
  );

}